### ISSUE TITLE
Plugin no longer works in gedit 40

### ISSUE THREAD

**Issue by enlightenedliberal1** [johnfactotum/gedit-restore-minimap#6]
On Debian, running gedit 40.1-1, the plugin shows up in the plugins dialog, but no map is displayed.

**Comment by johnfactotum** [comment]
Hmm. It works for me. Perhaps you have another plugin that conflicts with it?  Or does it give you any error messages?

**Comment by enlightenedliberal1** [comment]
`File "/home/user/.local/share/gedit/plugins/restore-minimap/restore_minimap.py", line 99, in do_activate
    self.tab.set_orientation(Gtk.Orientation.HORIZONTAL)
AttributeError: 'GeditViewCentering' object has no attribute 'set_orientation'`

**Comment by johnfactotum** [comment]
OK, I think I know what's going on here. Debian maintainers seem to have backported [fa587e0](https://gitlab.gnome.org/GNOME/gedit/-/commit/fa587e0) from gedit master/41 to 40.1. The commit changes the widget hierarchy, which breaks the plugin.

It's odd, though, because the commit apparently also brings back the minimap (and basically reverts pretty much all the changes made since 3.36).

So I think if you are using a version with that commit (41 or patched 40), then this plugin won't be needed anymore. You should be able to enable the minmap in the settings, the same way as in gedit 3.34 or earlier.

**Comment by enlightenedliberal1** [comment]
Ah, good catch. That indeed was the issue.

Thanks, and thanks for the plugin. It saved my life.

**Comment by cgcgcgcgcg** [comment]
I didn't use overview map in the past, so I had to look for it in Preferences, thank you.
![k_20220425-101932](https://user-images.githubusercontent.com/38960370/165039366-fadebeec-c629-4b3a-89d7-41d5c8fb5fc1.png)
